title: Road to Devops
description: Aiming to learn more about devops, used for writing articles and hosting projects on my own infrastructure
show_downloads: true
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
